/// Sign compatibility: does MKVI speak the same minisign dialect that the
/// official tool speaks?
///
/// ## What this file is for
///
/// The release key is produced by `minisign`, not by MKVI, so the only question
/// that matters before 0.2.0 can ship is whether the two agree. This file pins
/// that agreement against **one fixture produced by the official
/// implementation itself**, so a change in either dialect shows up as a failing
/// test rather than as a failed update on a user's machine.
///
/// ## The fixture is real, and here is exactly where it came from
///
/// Produced on 2026-09-26 by a throwaway crate outside this repository that
/// depended on **both** the `minisign` crate (v0.10.0, jedisct1's own Rust
/// implementation) and `mkvi_core` as a path dependency. The recipe is written
/// out in `docs/signing.md` so the fixture can be regenerated. The key pair was
/// created in memory, used once, and dropped: it was never written to disk and
/// it is not a release key. Only the **public** half and one signature over a
/// fixed public payload are recorded here, which is all a compatibility fixture
/// can safely contain.
///
/// The Windows `minisign` **CLI** is not installed on this machine and was
/// deliberately not installed; `docs/signing.md` records what `scoop` and
/// `winget` offer. The crate is the implementation the CLI is built on
/// (`rsign2` is described upstream as "a command-line tool reimplementing the
/// Minisign utility in Rust, and based on this crate"), so it is the right thing
/// to measure against - but that substitution is a judgement, not a proof, and
/// it is called out in the document rather than buried here.
///
/// ## What this file CANNOT prove, and why that is not fixable in Dart
///
/// It cannot check a single Ed25519 signature, and it does not pretend to:
///
/// * `app/pubspec.yaml` has **no cryptography dependency at all** - no
///   `ed25519`, no `cryptography`, nothing. Adding one to make a test able to
///   verify a signature would be adding a second implementation of the thing
///   `mkvi_core` exists to own, which `app/lib/update/update_verifier.dart`
///   explicitly forbids.
/// * The app **cannot call `mkvi_core`**. `flutter_rust_bridge` is not a
///   dependency of this package, `mkvi_core` exposes no C ABI, and the only
///   `SignatureVerifier` in `lib/` is `UnavailableSignatureVerifier`, which
///   refuses everything by design. So there is no Dart-reachable path to
///   `verify_artifact`.
///
/// The cryptographic verdict - "does an official signature pass MKVI's
/// verifier, and is a flipped byte rejected" - was therefore **measured by
/// running both implementations against each other**, and the result is
/// recorded in `docs/signing.md`. The short version, because it is the whole
/// point of this file existing: the *signature* is byte-for-byte compatible in
/// both directions, and the *key* is not, because MKVI's key classifier reads
/// the spec-mandated `Ed` key tag as "legacy".
library;

import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:mkvi/update/update_config.dart';
import 'package:mkvi/update/update_manifest.dart';
import 'package:mkvi/update/update_version.dart';

// ---------------------------------------------------------------------------
// Fixture: one official minisign key and one official signature over
// [officialPayloadB64]. Public material only.
// ---------------------------------------------------------------------------

/// The whole `.sig` file the official implementation wrote, base64 encoded -
/// the exact shape a Tauri feed stores in `platforms.*.signature` and the exact
/// shape `verify_artifact` is handed.
///
/// 277 bytes of text in four lines, and 277 is not a multiple of three, so this
/// value ends in `==`. That padding is load bearing; see the padding test.
// GENERATED by the compatibility probe; do not hand-edit. See docs/signing.md.
// GENERATED by the compatibility probe; do not hand-edit. See docs/signing.md.
const String officialSignatureB64 =
    'dW50cnVzdGVkIGNvbW1lbnQ6IE1LVkkgc2lnbiBjb21wYXRpYmlsaXR5IHByb2JlClJVUldK'
    'Sm1FWGRlQVdZZ3NMelhYNnd4ZFQ2T3krRDlPNlcvSU1wZUJ6NU5Eb2Q4NS9MbWkybU5vbUFq'
    'OFl0Q2hZRGUydVE3SUlzeUxXRTBGODdJODNKTDlqWGVic21lV0xBZz0KdHJ1c3RlZCBjb21t'
    'ZW50OiB0aW1lc3RhbXA6MTc5MDQyMjE1OQpLOUpZSUNBcm5EWkt5VUlaWDFKZDBPQ1FnalBu'
    'MnU3YzcxOEZrRlBqZXZDR0NJZmxlV2syUFgwVlozSjN2azZUT20wY1RiQXZSZFhRcjlRaXc3'
    'VDdEQT09Cg=='
    ;

const String officialPubFileB64 =
    'dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDU5ODBENzVEODQ5OTI0'
    'NTYKUldSV0pKbUVYZGVBV1cveUhzN3RuZjFKNGxXcDhMcmk4ck9VQVdsWjROUEljTkIxTlVo'
    'cWVyeDYK'
    ;

const String officialPubBareB64 =
    'RWRWJJmEXdeAWW/yHs7tnf1J4lWp8Lri8rOUAWlZ4NPIcNB1NUhqerx6'
    ;

const String officialPayloadB64 =
    'TUtWSSBzaWduIGNvbXBhdGliaWxpdHkgcHJvYmUgcGF5bG9hZC4gVGhpcyBpcyBOT1QgYSBy'
    'ZWxlYXNlIGFydGVmYWN0IGFuZCBOT1QgYSBzZWNyZXQuIEl0IGlzIGEgZml4ZWQgcHVibGlj'
    'IHN0cmluZywgcmVwZWF0ZWQgb25seSBzbyB0aGF0IHRoZSBCTEFLRTJiLTUxMiBwcmUtaGFz'
    'aCBzcGFucyBtb3JlIHRoYW4gb25lIDEyOCBieXRlIGJsb2NrLCB3aGljaCBpcyB0aGUgY2Fz'
    'ZSBhIHNpbmdsZS1ibG9jayBpbXBsZW1lbnRhdGlvbiBnZXRzIHdyb25nLiBBQUFBQUFBQUFB'
    'QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB'
    'QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBIEJCQkJC'
    'QkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJC'
    'QkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQiBDQ0ND'
    'Q0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0ND'
    'Q0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0M='
    ;

/// The prehashed algorithm tag, `ED`. The only signature form
/// `verify_artifact` accepts (`update.rs:151`).
const List<int> prehashedTag = <int>[0x45, 0x44];

/// The tag the **key** carries: `Ed`, not `ED` - and that is not a mistake in
/// the fixture. The published minisign format specifies `Ed` for the public key
/// and offers `ED` for the signature; `docs/signing.md` has the measurement and
/// the upstream wording.
const List<int> keyTag = <int>[0x45, 0x64];

// ---------------------------------------------------------------------------
// MKVI's reader rules, transcribed from crates/mkvi_core/src/update.rs.
//
// A TRANSCRIPTION, NOT THE RULE ITSELF. These are Dart copies of `algorithm_of`
// (update.rs:157), `signature_block` (:167), `key_block` (:176),
// `decode_public_key` (:190) and `key_is_legacy` (:129), so a Dart test can say
// what those rules do to the official bytes. They cannot stand in for the Rust
// code - the Ed25519 check is not here and is not reachable from here - so every
// test below is asserting about a rule, never about a signature being valid.
// ---------------------------------------------------------------------------

/// `str::lines()`: split on `\n`, then drop the single empty piece a trailing
/// newline leaves behind. The official writer terminates both files, so a plain
/// `split` would report five lines for a four line signature.
List<String> rustLines(String text) {
  final List<String> parts = text.split('\n');
  if (parts.isNotEmpty && parts.last.isEmpty) parts.removeLast();
  return parts;
}

/// `base64::engine::general_purpose::STANDARD`, which in Rust 0.22 requires
/// canonical padding. Whitespace and a missing `=` are both errors there, and
/// both are errors here.
List<int>? decodeStandard(String value) {
  if (value.length % 4 != 0) return null;
  try {
    return base64.decode(value);
  } on FormatException {
    return null;
  }
}

/// `algorithm_of`, update.rs:157. Line 1 is the payload and its first two bytes
/// are the tag.
List<int>? algorithmOf(String block) {
  final List<String> lines = rustLines(block);
  if (lines.length < 2) return null;
  final List<int>? decoded = decodeStandard(lines[1].trim());
  if (decoded == null || decoded.length < 2) return null;
  return decoded.sublist(0, 2);
}

/// `signature_block`, update.rs:167: base64 of a whole `.sig` file, read as
/// UTF-8 text.
String? signatureBlock(String signatureB64) {
  final List<int>? raw = decodeStandard(signatureB64.trim());
  if (raw == null) return null;
  try {
    return utf8.decode(raw);
  } on FormatException {
    return null;
  }
}

/// `key_block`, update.rs:176: either the file text itself, or base64 of it.
///
/// Note what this does **not** do: it cannot read the bare 42 byte form, because
/// 42 random bytes are not UTF-8. That is why `decode_public_key` tries the bare
/// form first, and the order is load bearing - see [decodePublicKeyShape].
String? keyBlock(String publicKeyB64) {
  final String trimmed = publicKeyB64.trim();
  if (trimmed.contains('untrusted comment:')) return trimmed;
  final List<int>? raw = decodeStandard(trimmed);
  if (raw == null) return null;
  try {
    return utf8.decode(raw);
  } on FormatException {
    return null;
  }
}

/// Which of the two shapes `decode_public_key` (update.rs:190) ends up taking,
/// or `null` for `UpdateError::MalformedKey`.
///
/// The order is the opposite of `key_is_legacy`'s, and the two functions
/// therefore disagree about a bare key: this one accepts it, the other calls it
/// legacy. Both orderings are faithful to the Rust.
String? decodePublicKeyShape(String publicKeyB64) {
  final String trimmed = publicKeyB64.trim();
  // `PublicKey::from_base64(trimmed)` is tried first, update.rs:192.
  final List<int>? bare = decodeStandard(trimmed);
  if (bare != null && bare.length == 42) return 'bare 42 bytes';
  // Only then `PublicKey::decode(&key_block(trimmed)?)`, update.rs:195.
  final String? block = keyBlock(trimmed);
  if (block == null) return null;
  final List<String> lines = rustLines(block);
  if (lines.length < 2) return null;
  final List<int>? decoded = decodeStandard(lines[1].trim());
  if (decoded == null || decoded.length != 42) return null;
  return 'whole .key.pub file';
}

/// `key_is_legacy`, update.rs:129. `null` stands for `UpdateError::MalformedKey`.
bool? keyIsLegacy(String publicKeyB64) {
  final String trimmed = publicKeyB64.trim();
  final List<int>? raw = decodeStandard(trimmed);
  if (raw != null) {
    try {
      final List<int>? tag = algorithmOf(utf8.decode(raw));
      if (tag != null) return _same(tag, keyTag);
    } on FormatException {
      // Not text: fall through to the bare-key reading, exactly as Rust does.
    }
    if (raw.length >= 2) return _same(raw.sublist(0, 2), keyTag);
  }
  final List<int>? direct = algorithmOf(trimmed);
  if (direct != null) return _same(direct, keyTag);
  return null;
}

bool _same(List<int> a, List<int> b) {
  if (a.length != b.length) return false;
  for (int i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

// ---------------------------------------------------------------------------

void main() {
  group('the official fixture is what the format says it is', () {
    test('the .sig file has the four lines the format requires', () {
      final String text = signatureBlock(officialSignatureB64)!;
      final List<String> lines = rustLines(text);

      expect(lines, hasLength(4));
      expect(lines[0], startsWith('untrusted comment: '));
      expect(lines[2], startsWith('trusted comment: '));
      // minisign-verify 0.3.0 rejects a block whose third line is not prefixed
      // `trusted comment: ` (`Signature::decode`), so this is load bearing
      // rather than cosmetic.
      expect(decodeStandard(lines[1].trim()), hasLength(74));
      expect(decodeStandard(lines[3].trim()), hasLength(64));
      // The official writer terminates the file. That trailing newline is part
      // of the bytes, which is why what goes into `latest.json` is base64 of the
      // whole file rather than of the payload alone.
      expect(text.endsWith('\n'), isTrue);
    });

    test('the signature is tagged ED, the only form MKVI accepts', () {
      final String text = signatureBlock(officialSignatureB64)!;
      expect(algorithmOf(text), prehashedTag);
    });

    test('the public key is 42 bytes and is tagged Ed, as the format says', () {
      final String text = keyBlock(officialPubFileB64)!;
      final List<String> lines = rustLines(text);
      expect(lines, hasLength(2));
      expect(lines[0], startsWith('untrusted comment: minisign public key: '));
      expect(algorithmOf(text), keyTag);
      expect(decodeStandard(lines[1].trim()), hasLength(42));
      // The bare form is the same 42 bytes, so the two shapes
      // `UpdateConfig.publicKeyB64` accepts really do name one key.
      expect(decodeStandard(lines[1].trim()), decodeStandard(officialPubBareB64));
    });

    test('the key id in the signature is the key id in the key', () {
      final List<int> signed = decodeStandard(
        rustLines(signatureBlock(officialSignatureB64)!)[1].trim(),
      )!;
      final List<int> key = decodeStandard(officialPubBareB64)!;
      // Bytes 2..10 of both blocks. minisign-verify refuses a mismatch with
      // `UnexpectedKeyId` before it hashes anything, so a fixture with the wrong
      // key id would be a fixture that can never verify.
      expect(signed.sublist(2, 10), key.sublist(2, 10));
    });

    test('the payload the fixture signs is the one that was signed', () {
      expect(decodeStandard(officialPayloadB64), hasLength(590));
    });
  });

  group("MKVI's reader rules, applied to the official bytes", () {
    test('the signature is readable and is the accepted algorithm', () {
      final String text = signatureBlock(officialSignatureB64)!;
      expect(algorithmOf(text), isNotNull);
      expect(_same(algorithmOf(text)!, prehashedTag), isTrue);
    });

    test('both accepted key shapes decode, through different branches', () {
      // Different branches on purpose. The bare form never reaches `key_block`
      // - 42 random bytes are not UTF-8 - so a reader that only implemented the
      // `.pub` file shape would pass a test written with a `.pub` fixture and
      // fail on the value a build is most likely to be given.
      expect(decodePublicKeyShape(officialPubBareB64), 'bare 42 bytes');
      expect(decodePublicKeyShape(officialPubFileB64), 'whole .key.pub file');
      expect(keyBlock(officialPubBareB64), isNull);
      expect(keyIsLegacy('base64 degil'), isNull);
    });

    test('canonical base64 padding is load bearing, not decoration', () {
      // This is what a well-meaning "clean up the build flag" edit produces, and
      // the Rust core rejects it: `general_purpose::STANDARD` requires the `=`.
      final String unpaddedSignature = officialSignatureB64.replaceAll('=', '');
      expect(officialSignatureB64.endsWith('=='), isTrue);
      expect(decodeStandard(unpaddedSignature), isNull);
      // And the value has to be the whole file, not a trimmed payload: drop the
      // comment lines and the algorithm tag is no longer on line 1.
      final List<String> payloadOnly = rustLines(signatureBlock(officialSignatureB64)!)
          .where((String line) => !line.startsWith('untrusted comment: '))
          .toList();
      expect(algorithmOf(payloadOnly.join('\n')), isNull);
    });

    // -----------------------------------------------------------------------
    // RECORDED MEASUREMENT - NOT AN ENDORSEMENT.
    //
    // Everything below this line documents a defect. It is written as a test so
    // that it cannot be quietly forgotten, and so that whoever fixes it cannot
    // fix it without this file going red and being updated on purpose.
    //
    // The measured facts, 2026-09-26, against official `minisign` crate 0.10.0:
    //
    //   * minisign's published format specification lists
    //     `signature_algorithm: Ed` for the **public key** and offers `ED` for
    //     the **signature**. The official implementation follows its own
    //     specification: both of its key generation paths,
    //     `generate_unencrypted_keypair()` and `generate_encrypted_keypair()`,
    //     write a key tagged `Ed`. Measured on both, above.
    //   * `minisign-verify` 0.3.0 - the crate MKVI actually verifies with -
    //     accepts **both** tags on a key (`PublicKey::from_base64`:
    //     `(0x45,0x64) | (0x45,0x44) => {}`). `allow_legacy` gates the
    //     *signature* algorithm only; it never inspects the key's tag.
    //   * So the key's tag carries no security meaning, and `key_is_legacy`
    //     reading it as "retired" is MKVI's own rule, not the format's.
    //     `verify_artifact` (update.rs:103) short-circuits on it, so **as
    //     written 0.2.0 refuses every key the official tool can produce.**
    //
    // The fix is not in this file and not in `app/`. It is
    // `crates/mkvi_core/src/update.rs:129` and `:103`, plus three Dart doc
    // comments that repeat the same misdiagnosis
    // (`app/lib/update/update_config.dart:158`, `update_preflight.dart:11`,
    // `update_verifier.dart`). One of them advises minting the key with
    // `minisign -W`, which cannot help: `-W` means "do not encrypt the secret
    // key", and the key it writes is tagged `Ed` either way.
    //
    // When that is fixed these two assertions are inverted and the block above
    // them is deleted. Do not delete the block first.
    // -----------------------------------------------------------------------
    test('RECORDED: the official key is called legacy by update.rs:129', () {
      expect(keyIsLegacy(officialPubBareB64), isTrue);
      expect(keyIsLegacy(officialPubFileB64), isTrue);
    });

    test('RECORDED: the tag is the only thing standing between the two', () {
      // `verify_artifact` returns `UpdateError::LegacyKey` before it ever looks
      // at the signature, so no official signature can be accepted under an
      // official key however it was produced. The measured exception: changing
      // the key's second tag byte from `d` to `D` by hand - an edit no tool
      // performs - is enough for the same official signature to be ACCEPTED.
      // That is the whole gap, and it is one byte wide.
      final List<int> raw = decodeStandard(officialPubBareB64)!;
      expect(_same(raw.sublist(0, 2), keyTag), isTrue);
      raw[1] = 0x44; // "Ed" -> "ED"
      expect(_same(raw.sublist(0, 2), prehashedTag), isTrue);
      expect(keyIsLegacy(base64.encode(raw)), isFalse);
    });
  });

  group('the value survives the Dart layer byte for byte', () {
    // The Dart layer is not allowed to interpret a signature - it carries it.
    // What it *is* responsible for is not mangling it on the way past, and the
    // official fixture is what makes that checkable: a stripped `=`, a trimmed
    // newline or a re-wrapped comment would all still be "a base64 string" to
    // any test written with a made-up fixture, and all three break the core.
    test('the feed hands the signature on unchanged', () {
      final Map<String, Object?> feed = <String, Object?>{
        'version': '0.2.1',
        'notes': 'Düzeltmeler',
        'platforms': <String, Object?>{
          windowsUpdateTarget: <String, Object?>{
            'url':
                'https://github.com/ancapenguin/mkvi/releases/download/v0.2.1/mkvi-setup.exe',
            'signature': officialSignatureB64,
          },
        },
      };
      final UpdateManifest parsed = parseUpdateManifest(
        utf8.encode(jsonEncode(feed)),
        ReleaseVersion.tryParse('0.2.0')!,
      );
      expect(parsed, isA<ManifestOffersRelease>());
      final UpdateOffer offer = (parsed as ManifestOffersRelease).offer;
      expect(offer.signature, officialSignatureB64);
    });

    test('the config keeps the key unchanged', () {
      final UpdateConfig config = UpdateConfig(
        currentVersion: '0.2.0',
        feedUrl: Uri.parse(
          'https://github.com/ancapenguin/mkvi/releases/latest/download/latest.json',
        ),
        publicKeyB64: officialPubFileB64,
      );
      expect(config.publicKeyB64, officialPubFileB64);
      // `hasReleaseKey` is a `trim().isNotEmpty`, so it must not be asked to
      // judge the shape. A key that reads as legacy is still a key that arrived,
      // and the preflight's next question is the one that is supposed to decide.
      expect(config.hasReleaseKey, isTrue);
      expect(config.isConfigured, isTrue);
    });
  });
}
