// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `open_core_with_store`

/// Opens the process core, restoring the device identity and the encrypted
/// history under `data_dir`.
///
/// Guarantees, in the order the core establishes them:
///
/// 1. The data directory exists.
/// 2. The encrypted history is opened **first**, so an install that already has
///    a peer is known to be paired *before* the identity is restored. A missing
///    secure-store entry is then reported as
///    [`CoreFailure::Security`] / `KeyringEntryMissing` instead of being topped
///    up with a fresh key, which is the failure that once made MKVI forget its
///    peer and ask for a pairing code again.
/// 3. The identity is restored, or minted only on a genuinely pristine install.
///
/// Fails with [`CoreFailure`] only. It never returns a half-opened core.
///
/// This is the constructor, not one of the seven domain calls; it is counted
/// separately because it exists to hand out the `&Core` the other seven take.
///
/// The handle is returned by value rather than as an `Arc<Core>` on purpose:
/// flutter_rust_bridge generates two unrelated Dart types for those, and Dart
/// could not pass what `open_core` returned straight back into the seven calls.
Future<Core> openCore({required String dataDir}) =>
    RustLib.instance.api.crateApiOpenCore(dataDir: dataDir);

/// Returns this device's Ed25519 public key.
///
/// **Guarantees:** the key is the one restored by [`open_core`] from the secure
/// store, so it is byte-for-byte stable across launches on the same install, and
/// it is the key [`sign`] will use. The private seed never leaves `mkvi_core`.
///
/// **Format:** unpadded standard base64 (RFC 4648 §5, no `=`), exactly what
/// `Core::public_key_base64` produces and what the Tauri shell's
/// `device_public_key` already put on the wire. `verify` accepts this shape.
Future<String> devicePublicKey({required Core core}) =>
    RustLib.instance.api.crateApiDevicePublicKey(core: core);

/// Signs `message` with this device's private key.
///
/// **Guarantees:** the returned signature is an Ed25519 signature over exactly
/// the bytes given, under the key [`device_public_key`] publishes, so
/// `verify(public_key, message, signature)` accepts it. The private seed is
/// never returned, copied out of the identity, or exposed in any form.
///
/// **Format:** unpadded standard base64, matching [`device_public_key`] and the
/// `sign_pairing` command the desktop shell already exposed. Padding is
/// deliberately absent because a 64-byte signature is 88 padded characters and 86
/// unpadded, and the peer protocol cannot be renegotiated by the Flutter port.
///
/// Cannot fail today; the `Result` is kept so a future key that needs
/// preparation has somewhere to report it without changing the Dart signature.
Future<String> sign({required Core core, required List<int> message}) =>
    RustLib.instance.api.crateApiSign(core: core, message: message);

/// Checks an Ed25519 signature against a peer-supplied public key.
///
/// **Guarantees:** returns `true` only when `signature` is a valid Ed25519
/// signature by `public_key` over exactly `message`. The core uses
/// `verify_strict`, so a signature produced under a weaker Ed25519 variant is
/// refused, not accepted.
///
/// **A malformed key or signature returns `false` rather than raising.** That is
/// a deliberate choice: if a bad encoding threw, a peer could tell "this key is
/// unparseable" apart from "this signature is wrong" and use the difference to
/// probe. Both are simply "not verified".
///
/// **Format:** [`device_public_key`]'s unpadded standard base64, for all three
/// byte arguments.
Future<bool> verify({
  required String publicKey,
  required List<int> message,
  required String signature,
}) => RustLib.instance.api.crateApiVerify(
  publicKey: publicKey,
  message: message,
  signature: signature,
);

/// Appends one message to the encrypted local history.
///
/// **Guarantees:** on `Ok` the message is committed to SQLite and sealed with
/// XChaCha20-Poly1305 under the history key; no plaintext is written to disk.
/// A duplicate `id` fails rather than overwriting, so a retried delivery is
/// visible as an error instead of silently replacing history.
///
/// An empty or longer-than-128-byte `id` is refused as
/// `CoreFailure::Security` / `InvalidMessageId` before any I/O.
Future<void> appendHistory({
  required Core core,
  required HistoryMessage message,
}) => RustLib.instance.api.crateApiAppendHistory(core: core, message: message);

/// Reads back the newest messages from the encrypted local history.
///
/// **Guarantees:** the result is ordered newest first by `sent_at_ms` and holds
/// at most `limit` messages; the core clamps `limit` to 500 itself, so a caller
/// asking for a million gets 500 rows rather than an allocation. Each row is
/// decrypted and authenticated, and a row that fails authentication fails the
/// whole call with `CoreFailure::Security` / `Crypto` rather than being skipped —
/// a partial list would look like lost history.
///
/// An empty result means the history is genuinely empty, not unreadable.
Future<List<HistoryMessage>> listHistory({
  required Core core,
  required int limit,
}) => RustLib.instance.api.crateApiListHistory(core: core, limit: limit);

/// Stores or replaces the paired peer.
///
/// **Guarantees:** on `Ok` the peer is sealed in the encrypted store and will be
/// returned by [`list_peers`]. Re-recording the same `public_key` replaces the
/// stored row, which is how a re-pairing is expressed.
///
/// Field shapes are validated before anything is written: a `public_key` that is
/// empty or longer than 128 bytes, a `discovery_id` that is not exactly 43
/// characters, or a `display_name` longer than 80 all fail as
/// `CoreFailure::Security` / `InvalidSecret`. The 43-character `discovery_id` is
/// the shape the rendezvous protocol mints (32 random bytes in unpadded base64).
Future<void> rememberPeer({required Core core, required KnownPeer peer}) =>
    RustLib.instance.api.crateApiRememberPeer(core: core, peer: peer);

/// Lists the paired peers, newest first.
///
/// **Guarantees:** every entry is decrypted and authenticated before it is
/// returned, and an entry that fails fails the whole call. MKVI pairs one device
/// with one peer, so a healthy install returns a list of length 0 or 1; the list
/// shape is kept because that is what the store holds.
Future<List<KnownPeer>> listPeers({required Core core}) =>
    RustLib.instance.api.crateApiListPeers(core: core);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Core>>
abstract class Core implements RustOpaqueInterface {}

/// One stored message, as it crosses the boundary.
///
/// Field names match the core's struct so the encrypted record format does not
/// change; the conversion is in [`From`] below.
class HistoryMessage {
  final String id;
  final String conversationId;
  final String senderDeviceId;
  final PlatformInt64 sentAtMs;
  final String body;

  const HistoryMessage({
    required this.id,
    required this.conversationId,
    required this.senderDeviceId,
    required this.sentAtMs,
    required this.body,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      senderDeviceId.hashCode ^
      sentAtMs.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          senderDeviceId == other.senderDeviceId &&
          sentAtMs == other.sentAtMs &&
          body == other.body;
}

/// One paired peer, as it crosses the boundary.
class KnownPeer {
  final String publicKey;
  final String discoveryId;
  final String displayName;
  final PlatformInt64 pairedAtMs;

  const KnownPeer({
    required this.publicKey,
    required this.discoveryId,
    required this.displayName,
    required this.pairedAtMs,
  });

  @override
  int get hashCode =>
      publicKey.hashCode ^
      discoveryId.hashCode ^
      displayName.hashCode ^
      pairedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnownPeer &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          discoveryId == other.discoveryId &&
          displayName == other.displayName &&
          pairedAtMs == other.pairedAtMs;
}
