// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class CoreFailure with _$CoreFailure implements FrbException {
  const CoreFailure._();

  /// The encrypted history mutex could not be taken.
  const factory CoreFailure.historyLocked({required String message}) =
      CoreFailure_HistoryLocked;

  /// The peer store mutex could not be taken.
  const factory CoreFailure.peerStoreLocked({required String message}) =
      CoreFailure_PeerStoreLocked;

  /// The file sink mutex could not be taken.
  const factory CoreFailure.fileSinkLocked({required String message}) =
      CoreFailure_FileSinkLocked;

  /// There is no open transfer for that id.
  const factory CoreFailure.noOpenTransfer({required String message}) =
      CoreFailure_NoOpenTransfer;

  /// The concurrent transfer cap was reached.
  const factory CoreFailure.tooManyTransfers({required String message}) =
      CoreFailure_TooManyTransfers;

  /// That transfer id is already open.
  const factory CoreFailure.duplicateTransfer({required String message}) =
      CoreFailure_DuplicateTransfer;

  /// The transfer exceeded the allowed size.
  const factory CoreFailure.transferTooLarge({required String message}) =
      CoreFailure_TransferTooLarge;

  /// `CoreError::Security`, carrying the inner case.
  const factory CoreFailure.security({required SecurityFailure failure}) =
      CoreFailure_Security;

  /// Operating system text, passed through unchanged.
  const factory CoreFailure.io({required String message}) = CoreFailure_Io;
}

@freezed
sealed class SecurityFailure with _$SecurityFailure {
  const SecurityFailure._();

  /// The operating system secret store itself refused the call.
  const factory SecurityFailure.secretStore({required String message}) =
      SecurityFailure_SecretStore;

  /// A required entry is gone while local data still depends on it.
  ///
  /// `name` is kept because the recovery differs per entry and the UI has to
  /// be able to name the one that is missing. This is the failure mode that
  /// must never be papered over by minting a replacement key.
  const factory SecurityFailure.keyringEntryMissing({
    required String name,
    required String message,
  }) = SecurityFailure_KeyringEntryMissing;

  /// The store accepted a write and then could not return the value, which is
  /// how a backend that degraded to an in-memory mock behaves.
  const factory SecurityFailure.secretStoreMissing({required String message}) =
      SecurityFailure_SecretStoreMissing;

  /// A stored secret could not be decoded.
  const factory SecurityFailure.invalidSecret({required String message}) =
      SecurityFailure_InvalidSecret;

  /// An authenticated-encryption or signing operation failed.
  const factory SecurityFailure.crypto({required String message}) =
      SecurityFailure_Crypto;

  /// The SQLite layer failed. `message` is the driver text, passed through.
  const factory SecurityFailure.database({required String message}) =
      SecurityFailure_Database;

  /// A stored record could not be (de)serialised.
  const factory SecurityFailure.serialization({required String message}) =
      SecurityFailure_Serialization;

  /// The caller supplied an empty or oversized message id.
  const factory SecurityFailure.invalidMessageId({required String message}) =
      SecurityFailure_InvalidMessageId;
}
