// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1465406893;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mkvi_bridge',
        ioDirectory: '../target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAppendHistory({
    required Core core,
    required HistoryMessage message,
  });

  Future<String> crateApiDevicePublicKey({required Core core});

  Future<List<HistoryMessage>> crateApiListHistory({
    required Core core,
    required int limit,
  });

  Future<List<KnownPeer>> crateApiListPeers({required Core core});

  Future<Core> crateApiOpenCore({required String dataDir});

  Future<void> crateApiRememberPeer({
    required Core core,
    required KnownPeer peer,
  });

  Future<String> crateApiSign({required Core core, required List<int> message});

  Future<bool> crateApiVerify({
    required String publicKey,
    required List<int> message,
    required String signature,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Core;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Core;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CorePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAppendHistory({
    required Core core,
    required HistoryMessage message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_box_autoadd_history_message(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_failure,
        ),
        constMeta: kCrateApiAppendHistoryConstMeta,
        argValues: [core, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppendHistoryConstMeta => const TaskConstMeta(
    debugName: "append_history",
    argNames: ["core", "message"],
  );

  @override
  Future<String> crateApiDevicePublicKey({required Core core}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDevicePublicKeyConstMeta,
        argValues: [core],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDevicePublicKeyConstMeta =>
      const TaskConstMeta(debugName: "device_public_key", argNames: ["core"]);

  @override
  Future<List<HistoryMessage>> crateApiListHistory({
    required Core core,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_history_message,
          decodeErrorData: sse_decode_core_failure,
        ),
        constMeta: kCrateApiListHistoryConstMeta,
        argValues: [core, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListHistoryConstMeta => const TaskConstMeta(
    debugName: "list_history",
    argNames: ["core", "limit"],
  );

  @override
  Future<List<KnownPeer>> crateApiListPeers({required Core core}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_known_peer,
          decodeErrorData: sse_decode_core_failure,
        ),
        constMeta: kCrateApiListPeersConstMeta,
        argValues: [core],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListPeersConstMeta =>
      const TaskConstMeta(debugName: "list_peers", argNames: ["core"]);

  @override
  Future<Core> crateApiOpenCore({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore,
          decodeErrorData: sse_decode_core_failure,
        ),
        constMeta: kCrateApiOpenCoreConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenCoreConstMeta =>
      const TaskConstMeta(debugName: "open_core", argNames: ["dataDir"]);

  @override
  Future<void> crateApiRememberPeer({
    required Core core,
    required KnownPeer peer,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_box_autoadd_known_peer(peer, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_failure,
        ),
        constMeta: kCrateApiRememberPeerConstMeta,
        argValues: [core, peer],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRememberPeerConstMeta => const TaskConstMeta(
    debugName: "remember_peer",
    argNames: ["core", "peer"],
  );

  @override
  Future<String> crateApiSign({
    required Core core,
    required List<int> message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_core_failure,
        ),
        constMeta: kCrateApiSignConstMeta,
        argValues: [core, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignConstMeta =>
      const TaskConstMeta(debugName: "sign", argNames: ["core", "message"]);

  @override
  Future<bool> crateApiVerify({
    required String publicKey,
    required List<int> message,
    required String signature,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publicKey, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_String(signature, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVerifyConstMeta,
        argValues: [publicKey, message, signature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyConstMeta => const TaskConstMeta(
    debugName: "verify",
    argNames: ["publicKey", "message", "signature"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Core => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Core => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore;

  @protected
  Core
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Core
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Core
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  HistoryMessage dco_decode_box_autoadd_history_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_history_message(raw);
  }

  @protected
  KnownPeer dco_decode_box_autoadd_known_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_known_peer(raw);
  }

  @protected
  SecurityFailure dco_decode_box_autoadd_security_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_security_failure(raw);
  }

  @protected
  CoreFailure dco_decode_core_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CoreFailure_HistoryLocked(message: dco_decode_String(raw[1]));
      case 1:
        return CoreFailure_PeerStoreLocked(message: dco_decode_String(raw[1]));
      case 2:
        return CoreFailure_FileSinkLocked(message: dco_decode_String(raw[1]));
      case 3:
        return CoreFailure_NoOpenTransfer(message: dco_decode_String(raw[1]));
      case 4:
        return CoreFailure_TooManyTransfers(message: dco_decode_String(raw[1]));
      case 5:
        return CoreFailure_DuplicateTransfer(
          message: dco_decode_String(raw[1]),
        );
      case 6:
        return CoreFailure_TransferTooLarge(message: dco_decode_String(raw[1]));
      case 7:
        return CoreFailure_Security(
          failure: dco_decode_box_autoadd_security_failure(raw[1]),
        );
      case 8:
        return CoreFailure_Io(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  HistoryMessage dco_decode_history_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return HistoryMessage(
      id: dco_decode_String(arr[0]),
      conversationId: dco_decode_String(arr[1]),
      senderDeviceId: dco_decode_String(arr[2]),
      sentAtMs: dco_decode_i_64(arr[3]),
      body: dco_decode_String(arr[4]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KnownPeer dco_decode_known_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return KnownPeer(
      publicKey: dco_decode_String(arr[0]),
      discoveryId: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
      pairedAtMs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  List<HistoryMessage> dco_decode_list_history_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_message).toList();
  }

  @protected
  List<KnownPeer> dco_decode_list_known_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_known_peer).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SecurityFailure dco_decode_security_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SecurityFailure_SecretStore(message: dco_decode_String(raw[1]));
      case 1:
        return SecurityFailure_KeyringEntryMissing(
          name: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 2:
        return SecurityFailure_SecretStoreMissing(
          message: dco_decode_String(raw[1]),
        );
      case 3:
        return SecurityFailure_InvalidSecret(
          message: dco_decode_String(raw[1]),
        );
      case 4:
        return SecurityFailure_Crypto(message: dco_decode_String(raw[1]));
      case 5:
        return SecurityFailure_Database(message: dco_decode_String(raw[1]));
      case 6:
        return SecurityFailure_Serialization(
          message: dco_decode_String(raw[1]),
        );
      case 7:
        return SecurityFailure_InvalidMessageId(
          message: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Core
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Core
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Core
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  HistoryMessage sse_decode_box_autoadd_history_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_history_message(deserializer));
  }

  @protected
  KnownPeer sse_decode_box_autoadd_known_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_known_peer(deserializer));
  }

  @protected
  SecurityFailure sse_decode_box_autoadd_security_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_security_failure(deserializer));
  }

  @protected
  CoreFailure sse_decode_core_failure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_HistoryLocked(message: var_message);
      case 1:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_PeerStoreLocked(message: var_message);
      case 2:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_FileSinkLocked(message: var_message);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_NoOpenTransfer(message: var_message);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_TooManyTransfers(message: var_message);
      case 5:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_DuplicateTransfer(message: var_message);
      case 6:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_TransferTooLarge(message: var_message);
      case 7:
        var var_failure = sse_decode_box_autoadd_security_failure(deserializer);
        return CoreFailure_Security(failure: var_failure);
      case 8:
        var var_message = sse_decode_String(deserializer);
        return CoreFailure_Io(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  HistoryMessage sse_decode_history_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_conversationId = sse_decode_String(deserializer);
    var var_senderDeviceId = sse_decode_String(deserializer);
    var var_sentAtMs = sse_decode_i_64(deserializer);
    var var_body = sse_decode_String(deserializer);
    return HistoryMessage(
      id: var_id,
      conversationId: var_conversationId,
      senderDeviceId: var_senderDeviceId,
      sentAtMs: var_sentAtMs,
      body: var_body,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KnownPeer sse_decode_known_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_String(deserializer);
    var var_discoveryId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_pairedAtMs = sse_decode_i_64(deserializer);
    return KnownPeer(
      publicKey: var_publicKey,
      discoveryId: var_discoveryId,
      displayName: var_displayName,
      pairedAtMs: var_pairedAtMs,
    );
  }

  @protected
  List<HistoryMessage> sse_decode_list_history_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<KnownPeer> sse_decode_list_known_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KnownPeer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_known_peer(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SecurityFailure sse_decode_security_failure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_SecretStore(message: var_message);
      case 1:
        var var_name = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_KeyringEntryMissing(
          name: var_name,
          message: var_message,
        );
      case 2:
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_SecretStoreMissing(message: var_message);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_InvalidSecret(message: var_message);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_Crypto(message: var_message);
      case 5:
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_Database(message: var_message);
      case 6:
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_Serialization(message: var_message);
      case 7:
        var var_message = sse_decode_String(deserializer);
        return SecurityFailure_InvalidMessageId(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_history_message(
    HistoryMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_history_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_known_peer(
    KnownPeer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_known_peer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_security_failure(
    SecurityFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_security_failure(self, serializer);
  }

  @protected
  void sse_encode_core_failure(CoreFailure self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CoreFailure_HistoryLocked(message: final message):
        sse_encode_i_32(0, serializer);
        sse_encode_String(message, serializer);
      case CoreFailure_PeerStoreLocked(message: final message):
        sse_encode_i_32(1, serializer);
        sse_encode_String(message, serializer);
      case CoreFailure_FileSinkLocked(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case CoreFailure_NoOpenTransfer(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
      case CoreFailure_TooManyTransfers(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
      case CoreFailure_DuplicateTransfer(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
      case CoreFailure_TransferTooLarge(message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(message, serializer);
      case CoreFailure_Security(failure: final failure):
        sse_encode_i_32(7, serializer);
        sse_encode_box_autoadd_security_failure(failure, serializer);
      case CoreFailure_Io(message: final message):
        sse_encode_i_32(8, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_history_message(
    HistoryMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.conversationId, serializer);
    sse_encode_String(self.senderDeviceId, serializer);
    sse_encode_i_64(self.sentAtMs, serializer);
    sse_encode_String(self.body, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_known_peer(KnownPeer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.discoveryId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_i_64(self.pairedAtMs, serializer);
  }

  @protected
  void sse_encode_list_history_message(
    List<HistoryMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_known_peer(
    List<KnownPeer> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_known_peer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_security_failure(
    SecurityFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SecurityFailure_SecretStore(message: final message):
        sse_encode_i_32(0, serializer);
        sse_encode_String(message, serializer);
      case SecurityFailure_KeyringEntryMissing(
        name: final name,
        message: final message,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(message, serializer);
      case SecurityFailure_SecretStoreMissing(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case SecurityFailure_InvalidSecret(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
      case SecurityFailure_Crypto(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
      case SecurityFailure_Database(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
      case SecurityFailure_Serialization(message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(message, serializer);
      case SecurityFailure_InvalidMessageId(message: final message):
        sse_encode_i_32(7, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class CoreImpl extends RustOpaque implements Core {
  // Not to be used by end users
  CoreImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Core,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Core,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CorePtr,
  );
}
